path: /Users/dani/Documents/LEARN/PYTHON/object-detection/content/data # dataset root dir
train: images/train # train images (relative to 'path')
val: images/val # val images (relative to 'path')

# Classes
nc: 1
names: ['duck']
