path: /Users/dani/Documents/LEARN/PYTHON/object-detection/content/data # dataset root dir
train: images/train # train images (relative to 'path')
val: images/val # val images (relative to 'path')

# Classes
nc: 74
names:
  0: 'Urobilinogen: 3.2'
  1: 'Urobilinogen: 16'
  2: 'Urobilinogen: 32+'
  3: 'Urobilinogen: 64++'
  4: 'Urobilinogen: 128+++'
  5: 'Bilirubin: Neg.'
  6: 'Bilirubin: Small - 17'
  7: 'Bilirubin: Moderate - 50'
  8: 'Bilirubin: Large - 100'
  9: 'Ketone: Neg.'
  10: 'Ketone: Trace - 0.5'
  11: 'Ketone: Small - 1.5'
  12: 'Ketone: Moderate - 4.0'
  13: 'Ketone: Large - 8.0'
  14: 'Ketone: Large - 16.0'
  15: 'Creatinine: 0.9'
  16: 'Creatinine: 4.4'
  17: 'Creatinine: 8.8'
  18: 'Creatinine: 17.7'
  19: 'Creatinine: 26.5'
  20: 'Blood: Neg.'
  21: 'Blood: Non hemolyzed 10Trace'
  22: 'Blood: Hemolyzed 10Trace'
  23: 'Blood: 25 Small'
  24: 'Blood: 80 Moderate'
  25: 'Blood: 200 Large'
  26: 'Protein: Neg.'
  27: 'Protein: Trace +-'
  28: 'Protein: 0.3 +'
  29: 'Protein: 1.0 ++'
  30: 'Protein: 3.0 +++'
  31: 'Protein: >20.0'
  32: 'Micro Albumin: 10'
  33: 'Micro Albumin: 30'
  34: 'Micro Albumin: 80'
  35: 'Micro Albumin: 150'
  36: 'Nitrite: Neg.'
  37: 'Nitrite: Positive'
  38: 'Leukocytes: Neg.'
  39: 'Leukocytes: Trace 15'
  40: 'Leukocytes: Small 70'
  41: 'Leukocytes: Moderate 125'
  42: 'Leukocytes: Large 500'
  43: 'Glucose: Neg.'
  44: 'Glucose: 5 Trace'
  45: 'Glucose: 15+'
  46: 'Glucose: 30++'
  47: 'Glucose: 60++'
  48: 'Glucose: 110++++'
  49: 'Specific Gravity: 1.000'
  50: 'Specific Gravity: 1.005'
  51: 'Specific Gravity: 1.010'
  52: 'Specific Gravity: 1.015'
  53: 'Specific Gravity: 1.020'
  54: 'Specific Gravity: 1.025'
  55: 'Specific Gravity: 1.030'
  56: 'pH: 5.0'
  57: 'pH: 6.0'
  58: 'pH: 6.5'
  59: 'pH: 7.0'
  60: 'pH: 7.5'
  61: 'pH: 8.0'
  62: 'pH: 8.5'
  63: 'Ascorbate: 0'
  64: 'Ascorbate: 0.6'
  65: 'Ascorbate: 1.4'
  66: 'Ascorbate: 2.8'
  67: 'Ascorbate: 5.0'
  68: 'Calcium: <=1.0'
  69: 'Calcium: 2.5'
  70: 'Calcium: 5.0'
  71: 'Calcium: 7.5'
  72: 'Calcium: >=10'
  73: Dipstick Urine Test Card
